import google.generativeai as genai
from config import Config

# Configure the Gemini API key
if Config.GEMINI_API_KEY:
    genai.configure(api_key=Config.GEMINI_API_KEY)
else:
    raise ValueError("GEMINI_API_KEY is not set in the environment variables.")

def _format_history(history: list) -> list:
    """
    Helper to translate stored JSON history list to Gemini content blocks.
    """
    gemini_history = []
    if history:
        for pair in history:
            user_msg = pair.get("user", "")
            assistant_msg = pair.get("assistant", "")
            if user_msg and assistant_msg:
                gemini_history.append({"role": "user", "parts": [user_msg]})
                gemini_history.append({"role": "model", "parts": [assistant_msg]})
    return gemini_history

def generate_gemini_response(prompt: str, history: list = None) -> str:
    """
    Sends the prompt to Google Gemini API along with conversation history 
    context, and returns the generated response.
    
    Args:
        prompt (str): The user's input message.
        history (list, optional): Previous conversation history as list of dicts.
        
    Returns:
        str: The response text generated by Gemini.
    """
    try:
        model = genai.GenerativeModel(Config.GEMINI_MODEL)
        gemini_history = _format_history(history)
        
        chat_session = model.start_chat(history=gemini_history)
        response = chat_session.send_message(prompt)
        
        if response and response.text:
            return response.text
        else:
            return "No response text was generated by the model."
            
    except Exception as e:
        error_msg = str(e)
        print(f"Error in gemini_service: {error_msg}")
        if "429" in error_msg:
            raise Exception("Google API Rate Limit Exceeded. Please wait a moment and try again.")
        elif "API_KEY_INVALID" in error_msg or "API key not valid" in error_msg:
            raise Exception("Invalid Google Gemini API Key. Please check your .env file.")
        raise Exception(f"Gemini API Error: {error_msg}")

def generate_gemini_response_with_search(prompt: str, history: list, search_context: str) -> str:
    """
    Feeds web search context to Gemini as grounding data to generate
    an up-to-date answer for real-time information queries.
    
    Args:
        prompt (str): The user's original query.
        history (list): Previous conversation history.
        search_context (str): Structured text summarizing the Custom Search API results.
        
    Returns:
        str: Grounded response text generated by Gemini.
    """
    try:
        model = genai.GenerativeModel(Config.GEMINI_MODEL)
        gemini_history = _format_history(history)
        
        # Start the chat session with conversation history
        chat_session = model.start_chat(history=gemini_history)
        
        # Construct the grounding prompt instructing Gemini to use the search results
        grounded_prompt = (
            f"You are GeminiLive, an AI assistant with access to real-time search results.\n\n"
            f"Here are the top web search results for the user's query:\n"
            f"=========================================\n"
            f"{search_context}\n"
            f"=========================================\n\n"
            f"Instructions:\n"
            f"1. Use the provided search results to answer the user's query.\n"
            f"2. Cite facts from the snippets above when formulating your answer.\n"
            f"3. Make your answer informative, up-to-date, and clear.\n\n"
            f"User query: {prompt}"
        )
        
        # Send the detailed grounding prompt to the chat session
        response = chat_session.send_message(grounded_prompt)
        
        if response and response.text:
            return response.text
        else:
            return "No response text was generated by the model."
            
    except Exception as e:
        error_msg = str(e)
        print(f"Error in gemini_service (search context): {error_msg}")
        if "429" in error_msg:
            raise Exception("Google API Rate Limit Exceeded. Please wait a moment and try again.")
        elif "API_KEY_INVALID" in error_msg or "API key not valid" in error_msg:
            raise Exception("Invalid Google Gemini API Key. Please check your .env file.")
        raise Exception(f"Gemini API Error: {error_msg}")
